// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/appsinstalled/appsinstalled.proto

/*
Package appsinstalled is a generated protocol buffer package.
It is generated from these files:
	src/appsinstalled/appsinstalled.proto
It has these top-level messages:
	UserApps
*/
package appsinstalled

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserApps struct {
	Apps             []uint32 `protobuf:"varint,1,rep,name=apps" json:"apps,omitempty"`
	Lat              *float64 `protobuf:"fixed64,2,opt,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,3,opt,name=lon" json:"lon,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserApps) Reset()                    { *m = UserApps{} }
func (m *UserApps) String() string            { return proto.CompactTextString(m) }
func (*UserApps) ProtoMessage()               {}
func (*UserApps) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserApps) GetApps() []uint32 {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *UserApps) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *UserApps) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func init() {
	proto.RegisterType((*UserApps)(nil), "UserApps")
}

func init() { proto.RegisterFile("src/appsinstalled/appsinstalled.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2d, 0x2e, 0x4a, 0xd6,
	0x4f, 0x2c, 0x28, 0x28, 0xce, 0xcc, 0x2b, 0x2e, 0x49, 0xcc, 0xc9, 0x49, 0x4d, 0x41, 0xe5, 0xe9,
	0x15, 0x14, 0xe5, 0x97, 0xe4, 0x2b, 0x39, 0x71, 0x71, 0x84, 0x16, 0xa7, 0x16, 0x39, 0x16, 0x14,
	0x14, 0x0b, 0x09, 0x71, 0xb1, 0x80, 0x94, 0x48, 0x30, 0x2a, 0x30, 0x6b, 0xf0, 0x06, 0x81, 0xd9,
	0x42, 0x02, 0x5c, 0xcc, 0x39, 0x89, 0x25, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0x8c, 0x41, 0x20, 0x26,
	0x58, 0x24, 0x3f, 0x4f, 0x82, 0x19, 0x2a, 0x92, 0x9f, 0x07, 0x08, 0x00, 0x00, 0xff, 0xff, 0x89,
	0x33, 0x96, 0x00, 0x6b, 0x00, 0x00, 0x00,
}